crs_country = {
 '130': ('DZ', 'Algeria'),
 '133': ('LY', 'Libya'),
 '136': ('MA', 'Morocco'),
 '139': ('TN', 'Tunisia'),
 '142': ('EG', 'Egypt'),
 '218': ('ZA', 'South Africa'),
 '225': ('AO', 'Angola'),
 '227': ('BW', 'Botswana'),
 '228': ('BI', 'Burundi'),
 '229': ('CM', 'Cameroon'),
 '230': ('CV', 'Cape Verde'),
 '231': ('CF', 'Central African Rep.'),
 '232': ('TD', 'Chad'),
 '233': ('KM', 'Comoros'),
 '234': ('CG', 'Congo, Rep.'),
 '235': ('CD', 'Congo, Dem. Rep.'),
 '236': ('BJ', 'Benin'),
 '238': ('ET', 'Ethiopia'),
 '239': ('GA', 'Gabon'),
 '240': ('GM', 'Gambia'),
 '241': ('GH', 'Ghana'),
 '243': ('GN', 'Guinea'),
 '244': ('GW', 'Guinea-Bissau'),
 '245': ('GQ', 'Equatorial Guinea'),
 '247': ('CI', "Cote d'Ivoire"),
 '248': ('KE', 'Kenya'),
 '249': ('LS', 'Lesotho'),
 '251': ('LR', 'Liberia'),
 '252': ('MG', 'Madagascar'),
 '253': ('MW', 'Malawi'),
 '255': ('ML', 'Mali'),
 '256': ('MR', 'Mauritania'),
 '257': ('MU', 'Mauritius'),
 '258': ('YT', 'Mayotte'),
 '259': ('MZ', 'Mozambique'),
 '260': ('NE', 'Niger'),
 '261': ('NG', 'Nigeria'),
 '265': ('ZW', 'Zimbabwe'),
 '266': ('RW', 'Rwanda'),
 '268': ('ST', 'Sao Tome & Principe'),
 '269': ('SN', 'Senegal'),
 '270': ('SC', 'Seychelles'),
 '271': ('ER', 'Eritrea'),
 '272': ('SL', 'Sierra Leone'),
 '273': ('SO', 'Somalia'),
 '274': ('DJ', 'Djibouti'),
 '275': ('NA', 'Namibia'),
 '276': ('SH', 'St. Helena'),
 '278': ('SD', 'Sudan'),
 '280': ('SZ', 'Swaziland'),
 '282': ('TZ', 'Tanzania'),
 '283': ('TG', 'Togo'),
 '285': ('UG', 'Uganda'),
 '287': ('BF', 'Burkina Faso'),
 '288': ('ZM', 'Zambia'),
 '329': ('BB', 'Barbados'),
 '336': ('CR', 'Costa Rica'),
 '338': ('CU', 'Cuba'),
 '340': ('DO', 'Dominican Republic'),
 '342': ('SV', 'El Salvador'),
 '347': ('GT', 'Guatemala'),
 '349': ('HT', 'Haiti'),
 '351': ('HN', 'Honduras'),
 '352': ('BZ', 'Belize'),
 '354': ('JM', 'Jamaica'),
 '358': ('MX', 'Mexico'),
 '364': ('NI', 'Nicaragua'),
 '366': ('PA', 'Panama'),
 '375': ('TT', 'Trinidad and Tobago'),
 '376': ('AI', 'Anguilla'),
 '377': ('AG', 'Antigua and Barbuda'),
 '378': ('DM', 'Dominica'),
 '381': ('GD', 'Grenada'),
 '382': ('KN', 'St. Kitts-Nevis'),
 '383': ('LC', 'St. Lucia'),
 '384': ('VC', 'St.Vincent & Grenadines'),
 '385': ('MS', 'Montserrat'),
 '425': ('AR', 'Argentina'),
 '428': ('BO', 'Bolivia'),
 '431': ('BR', 'Brazil'),
 '434': ('CL', 'Chile'),
 '437': ('CO', 'Colombia'),
 '440': ('EC', 'Ecuador'),
 '446': ('GY', 'Guyana'),
 '451': ('PY', 'Paraguay'),
 '454': ('PE', 'Peru'),
 '457': ('SR', 'Suriname'),
 '460': ('UY', 'Uruguay'),
 '463': ('VE', 'Venezuela'),
 '540': ('IR', 'Iran'),
 '543': ('IQ', 'Iraq'),
 '549': ('JO', 'Jordan'),
 '55': ('TR', 'Turkey'),
 '550': ('PS', 'Palestinian Adm. Areas'),
 '555': ('LB', 'Lebanon'),
 '558': ('OM', 'Oman'),
 '57': ('XK', 'Kosovo'),
 '573': ('SY', 'Syria'),
 '580': ('YE', 'Yemen'),
 '610': ('AM', 'Armenia'),
 '611': ('AZ', 'Azerbaijan'),
 '612': ('GE', 'Georgia'),
 '613': ('KZ', 'Kazakhstan'),
 '614': ('KG', 'Kyrgyz Republic'),
 '615': ('TJ', 'Tajikistan'),
 '616': ('TM', 'Turkmenistan'),
 '617': ('UZ', 'Uzbekistan'),
 '62': ('HR', 'Croatia'),
 '625': ('AF', 'Afghanistan'),
 '63': ('RS', 'Serbia'),
 '630': ('BT', 'Bhutan'),
 '635': ('MM', 'Myanmar'),
 '64': ('BA', 'Bosnia-Herzegovina'),
 '640': ('LK', 'Sri Lanka'),
 '645': ('IN', 'India'),
 '65': ('ME', 'Montenegro'),
 '655': ('MV', 'Maldives'),
 '66': ('MK', 'Macedonia, FYR'),
 '660': ('NP', 'Nepal'),
 '665': ('PK', 'Pakistan'),
 '666': ('BD', 'Bangladesh'),
 '71': ('AL', 'Albania'),
 '728': ('KH', 'Cambodia'),
 '730': ('CN', 'China'),
 '738': ('ID', 'Indonesia'),
 '740': ('KP', 'Korea, Dem. Rep.'),
 '745': ('LA', 'Laos'),
 '751': ('MY', 'Malaysia'),
 '753': ('MN', 'Mongolia'),
 '755': ('PH', 'Philippines'),
 '764': ('TH', 'Thailand'),
 '765': ('TL', 'Timor-Leste'),
 '769': ('VN', 'Viet Nam'),
 '831': ('CK', 'Cook Islands'),
 '832': ('FJ', 'Fiji'),
 '836': ('KI', 'Kiribati'),
 '845': ('NR', 'Nauru'),
 '85': ('UA', 'Ukraine'),
 '854': ('VU', 'Vanuatu'),
 '856': ('NU', 'Niue'),
 '859': ('MH', 'Marshall Islands'),
 '86': ('BY', 'Belarus'),
 '860': ('FM', 'Micronesia, Fed. States'),
 '861': ('PW', 'Palau'),
 '862': ('PG', 'Papua New Guinea'),
 '866': ('SB', 'Solomon Islands'),
 '868': ('TK', 'Tokelau'),
 '870': ('TO', 'Tonga'),
 '872': ('TV', 'Tuvalu'),
 '876': ('WF', 'Wallis & Futuna'),
 '880': ('WS', 'Samoa'),
 '93': ('MD', 'Moldova'),
 'Recipient code': ('ISO-2', 'Recipient name (EN)')
}

crs_region = {
 '189': 'North of Sahara, regional',
 '289': 'South of Sahara, regional',
 '298': 'Africa, regional',
 '380': 'West Indies, regional',
 '389': 'North & Central America, regional',
 '489': 'South America, regional',
 '498': 'America, regional',
 '589': 'Middle East, regional',
 '619': 'Central Asia, regional',
 '679': 'South Asia, regional',
 '689': 'South & Central Asia, regional',
 '789': 'Far East Asia, regional',
 '798': 'Asia, regional',
 '88': 'States Ex-Yugoslavia',
 '889': 'Oceania, regional',
 '89': 'Europe, regional',
 '998': 'Bilateral, unspecified'
}
